# Generated by Django 5.1 on 2024-11-21 17:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambalaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, unique=True)),
                ('material', models.CharField(choices=[('plastic', 'Plastic'), ('hartie', 'Hartie'), ('carton', 'Carton')])),
                ('pret', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30, unique=True)),
                ('calorii', models.PositiveIntegerField(null=True)),
                ('unitate', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_cafenea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, unique=True)),
                ('furnizor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, null=True, unique=True)),
                ('adresa', models.TextField(null=True)),
                ('nr_angajati', models.IntegerField(null=True)),
                ('telefon', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numărul de telefon trebuie să înceapă cu +34 și să fie urmat de 9 cifre.', regex='^\\+34\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Locatie_exemplu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nr', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, unique=True)),
                ('pret', models.FloatField()),
                ('cantitate', models.PositiveIntegerField()),
                ('marime', models.CharField(choices=[('regular', 'regular'), ('large', 'large')], default='regular', max_length=10)),
                ('timp_preparare', models.PositiveIntegerField(default=1)),
                ('ingrediente_desert', models.ManyToManyField(to='aplicatie_ex.ingredient_cafenea')),
            ],
        ),
        migrations.CreateModel(
            name='Bautura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, unique=True)),
                ('pret', models.FloatField()),
                ('disponibila', models.BooleanField()),
                ('marime', models.CharField(choices=[('regular', 'regular'), ('large', 'large')], default='regular', max_length=10)),
                ('timp_preparare', models.PositiveIntegerField(default=2)),
                ('ingrediente_bautura', models.ManyToManyField(to='aplicatie_ex.ingredient_cafenea')),
            ],
        ),
        migrations.CreateModel(
            name='Mancare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, unique=True)),
                ('pret', models.FloatField()),
                ('cantitate', models.PositiveIntegerField()),
                ('marime', models.CharField(choices=[('regular', 'regular'), ('large', 'large')], default='regular', max_length=10)),
                ('timp_preparare', models.PositiveIntegerField(default=8)),
                ('ingrediente_mancare', models.ManyToManyField(to='aplicatie_ex.ingredient_cafenea')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacreare', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('anulata', 'anulata'), ('confirmata', 'confirmata'), ('finalizata', 'finalizata')], default='in asteptare', max_length=20)),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=100)),
                ('telefon', models.IntegerField(blank=True)),
                ('metoda_livrare', models.CharField(choices=[('pickup cafenea', 'pickup cafenea'), ('livrare la domiciliu', 'livrare la domiciliu')], max_length=50)),
                ('adresa_livrare', models.CharField(blank=True, max_length=150, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metoda_plata', models.CharField(choices=[('numerar', 'Numerar'), ('card', 'Card Online')], max_length=50)),
                ('timp_pregatire', models.IntegerField(blank=True, null=True)),
                ('bauturi', models.ManyToManyField(blank=True, to='aplicatie_ex.bautura')),
                ('deserturi', models.ManyToManyField(blank=True, to='aplicatie_ex.desert')),
                ('micdejuns', models.ManyToManyField(blank=True, to='aplicatie_ex.mancare')),
            ],
        ),
        migrations.CreateModel(
            name='Prajitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20, unique=True)),
                ('descriere', models.TextField(null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gramaj', models.PositiveIntegerField()),
                ('temperatura', models.IntegerField()),
                ('tip_produs', models.CharField(choices=[('comanda speciala', 'Comanda speciala'), ('aniversara', 'Aniversara'), ('editie limitata', 'Editie limitata'), ('pentru copii', 'Pentru copii'), ('dietetica', 'Dietetica'), ('comuna', 'Comuna')])),
                ('calorii', models.IntegerField()),
                ('categorie', models.CharField(choices=[('cofetarie', 'Cofetarie'), ('patiserie', 'Patiserie'), ('gelaterie', 'Gelaterie')], default='comuna')),
                ('pt_diabetici', models.BooleanField()),
                ('ambalaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicatie_ex.ambalaj')),
                ('ingrediente', models.ManyToManyField(to='aplicatie_ex.ingredient')),
            ],
        ),
    ]
