# Generated by Django 5.1 on 2024-11-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='datanasterii',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gen',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nr_puncte',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
