# Generated by Django 5.1 on 2024-11-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0002_customuser_adresa_customuser_datanasterii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='locatie_fav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicatie_ex.locatie'),
        ),
    ]
