# Generated by Django 5.1 on 2024-12-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0009_promotii'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancare',
            name='categorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
