# Generated by Django 5.1 on 2024-12-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0011_alter_promotii_data_creare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotii',
            name='nume',
            field=models.CharField(blank=True, default='Promotie', max_length=20),
        ),
    ]
