# Generated by Django 5.1 on 2024-12-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0012_alter_promotii_nume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mancare',
            options={'permissions': [('vizualizeaza_oferta', 'Vizualizarea ofertei la micdejun')]},
        ),
    ]
