# Generated by Django 5.1 on 2024-12-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0013_alter_mancare_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mancare',
            options={},
        ),
    ]
