# Generated by Django 5.1 on 2024-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0014_alter_mancare_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancare',
            name='marime',
            field=models.CharField(choices=[('regular', 'regular'), ('large', 'large')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mancare',
            name='timp_preparare',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
