# Generated by Django 5.1 on 2024-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0015_alter_mancare_marime_alter_mancare_timp_preparare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancare',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
