# Generated by Django 5.1 on 2024-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0016_alter_mancare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient_cafenea',
            name='micdejuns',
            field=models.ManyToManyField(blank=True, related_name='micdejuns', to='aplicatie_ex.mancare'),
        ),
    ]
