# Generated by Django 5.1 on 2024-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0018_alter_ingredient_cafenea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
