# Generated by Django 5.1 on 2024-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0020_mancare_actualizat_la'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
