# Generated by Django 5.1 on 2024-12-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0022_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_block_users', 'Can block or unblock users'), ('can_change_data', 'Can change data users')]},
        ),
    ]
