# Generated by Django 5.1 on 2024-12-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0023_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='adresa_livrare',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='bauturi',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='deserturi',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='locatie_livrare',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='metoda_livrare',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='metoda_plata',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='micdejuns',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='prenume',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='timp_pregatire',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='total',
        ),
        migrations.AddField(
            model_name='comanda',
            name='id_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='produse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comenzi',
            field=models.ManyToManyField(blank=True, related_name='comenzi', to='aplicatie_ex.comanda'),
        ),
    ]
