# Generated by Django 5.1 on 2024-12-18 16:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0024_remove_comanda_adresa_livrare_remove_comanda_bauturi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='datacreare',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='id_user',
        ),
        migrations.AddField(
            model_name='comanda',
            name='data_comenzii',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comanda',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='produse',
        ),
        migrations.CreateModel(
            name='ComandaDetaliu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField()),
                ('pret_per_unitate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_ex.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_ex.mancare')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='produse',
            field=models.ManyToManyField(null=True, through='aplicatie_ex.ComandaDetaliu', to='aplicatie_ex.mancare'),
        ),
    ]
