# Generated by Django 5.1 on 2024-12-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0026_alter_comanda_data_comenzii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='data_comenzii',
        ),
        migrations.AddField(
            model_name='comanda',
            name='datavizualizare',
            field=models.DateField(blank=True, null=True),
        ),
    ]
