# Generated by Django 5.1 on 2025-01-09 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0029_elev_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('anul_inscrierii', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='produse',
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=30)),
                ('numar_credite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_ex.student')),
            ],
        ),
    ]
