# Generated by Django 5.1 on 2025-01-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_ex', '0030_student_remove_comanda_produse_curs'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicatie_ex.student'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='numar_credite',
            field=models.IntegerField(),
        ),
    ]
